driver:
  name: webdriver.chrome.driver
  path: C:\Users\ghkvud-home\Downloads\chromedriver_win32\chromedriver.exe

parameter:
  default:
    baseUrl: https://www.kbchachacha.com/public/search/main.kbc#!?page=
    startPage: 1
    endPage: 400
    
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: digital
    password: digital
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: trace
#    org.hibernate.SQL: debug

