driver:
  name: webdriver.chrome.driver
  path: C:\Users\LG\Desktop\유틸리티\chromedriver.exe
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: digital
    password: digital
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: trace
#    org.hibernate.SQL: debug

