driver:
  name: webdriver.chrome.driver
  path: C:\Users\ghkvud-home\Downloads\chromedriver_win32\chromedriver.exe
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: digital3
    password: digital3
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug