driver:
  name: webdriver.chrome.driver
  path: C:\Users\ghkvud-home\Downloads\chromedriver_win32\chromedriver.exe


parameter:
  default:
    baseUrl: https://www.kbchachacha.com/public/search/main.kbc#!?page=
    startPage: 1
    endPage: 10

spring:
  datasource:
    url: jdbc:mysql://localhost/digital?serverTimezone=UTC
    username: digital
    password: digital
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
