driver:
  name: webdriver.chrome.driver
    path: C:\Users\ghkvud-home\Downloads\chromedriver_win32\chromedriver.exe
#  path: /usr/bin/chromedriver


parameter:
  default:
#    baseUrl: https://www.kbchachacha.com/public/search/main.kbc#!?page=
    baseUrl: https://www.kbchachacha.com/public/search/main.kbc#!?makerCode=%s&classCode=%s&page=%s
    startPage: 1
    endPage: 10

spring:
  datasource:
    url: jdbc:mysql://localhost/digital?serverTimezone=UTC
    username: ENC(BCehGQz8lMngVmlKC9TZPg==)
    password: ENC(ocednKSp/ah0aOagHU0xUQ==)
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password: digital

